# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqFYIvOaoa1LQjbuDMOWNqOsMPjI9Mui
"""

!pip install pandas clean-text --quiet

import pandas as pd
from google.colab import files
from cleantext import clean

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
data = pd.read_csv(file_name)

columns = data.columns.tolist()
text_column = None
for candidate in ['text', 'full_text', 'tweet', 'tweet_text']:
    if candidate in columns:
        text_column = candidate
        break
if not text_column:
    text_column = columns[0]

def clean_tweet_text(text):
    if pd.isna(text):
        return ""
    cleaned = clean(str(text),
        lower=True,
        no_urls=True,
        no_emails=True,
        no_emoji=True,
        no_punct=False
    )
    cleaned = ' '.join(word for word in cleaned.split() if not word.startswith('@'))
    return cleaned

data['clean_text'] = data[text_column].apply(clean_tweet_text)

output_file = "TRAF101_cleaned_data.csv"
data[['clean_text']].to_csv(output_file, index=False)
files.download(output_file)

!pip install transformers torch --quiet

import pandas as pd
from google.colab import files
from transformers import pipeline

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
data = pd.read_csv(file_name)

data = data.dropna(subset=['clean_text'])

sentiment_analyzer = pipeline("sentiment-analysis", truncation=True)

sample_data = data.head(10).copy()
results = sentiment_analyzer(sample_data['clean_text'].tolist())

for i, text in enumerate(sample_data['clean_text']):
    print(f"Tweet: {text}")
    label = results[i]['label']
    confidence = round(results[i]['score'] * 100, 1)

    if label == 'NEGATIVE':
        print(f"AI Decision: 🔴 NEGATIVE ({confidence}% confidence)")
    else:
        print(f"AI Decision: 🟢 POSITIVE ({confidence}% confidence)")

    print("-" * 60)

import pandas as pd
import matplotlib.pyplot as plt
from transformers import pipeline

sentiment_analyzer = pipeline("sentiment-analysis", truncation=True)

analysis_data = data.dropna(subset=['clean_text'])
texts = analysis_data['clean_text'].tolist()

results = sentiment_analyzer(texts)

positive_count = sum(1 for result in results if result['label'] == 'POSITIVE')
negative_count = sum(1 for result in results if result['label'] == 'NEGATIVE')

labels = ['Positive / Supportive', 'Negative / Complaining']
counts = [positive_count, negative_count]
colors = ['#2ecc71', '#e74c3c']

plt.figure(figsize=(8, 6))
plt.pie(counts, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140, shadow=True, explode=(0.1, 0))
plt.title('TRAF101: Social Media Traffic Safety Sentiment Analysis')
plt.axis('equal')

plt.savefig("Sentiment_Analysis_Chart.png")
print("Chart generated and saved as 'Sentiment_Analysis_Chart.png'!")
plt.show()

import os
import urllib.request

print("1/4: Installing required libraries (This may take 2-3 minutes, PLEASE DO NOT INTERRUPT!)...")
!pip install transformers torch streamlit -q
!npm install -g localtunnel > /dev/null

import pandas as pd
from transformers import pipeline

print("\n2/4: Checking data...")
df = pd.read_csv("TRAF101_cleaned_data.csv")

if 'sentiment' not in df.columns:
    print("-> AI is reading and labeling tweets (Please wait)...")
    df = df.dropna(subset=['clean_text'])
    sentiment_analyzer = pipeline("sentiment-analysis", truncation=True)
    results = sentiment_analyzer(df['clean_text'].astype(str).tolist())
    df['sentiment'] = [result['label'] for result in results]
    df.to_csv("TRAF101_cleaned_data.csv", index=False)
    print("-> Labeling completed and saved!")
else:
    print("-> Data is already labeled, perfect! Proceeding directly to the dashboard...")

print("\n3/4: Creating Streamlit web dashboard...")
with open("app.py", "w", encoding="utf-8") as f:
    f.write("""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Traffic Safety NLP Dashboard", layout="wide")
st.title("📊 Traffic Safety Discourse Analysis Dashboard")
st.markdown("Interactive social media text mining and sentiment distribution platform.")

try:
    df = pd.read_csv("TRAF101_cleaned_data.csv")

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Total Tweets Analyzed", len(df))
    with col2:
        neg_count = len(df[df['sentiment'] == 'NEGATIVE'])
        st.metric("Negative Sentiment Volume", neg_count)

    st.markdown("---")

    # Filtering Menu
    selected_sentiment = st.radio("Filter Tweets by Sentiment:", ["ALL", "POSITIVE", "NEGATIVE"], horizontal=True)

    left_column, right_column = st.columns([1, 2])

    with left_column:
        st.subheader("💡 Distribution Metric")
        fig, ax = plt.subplots(figsize=(5, 5))

        sentiment_counts = df['sentiment'].value_counts()
        ax.pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=140, colors=['#e74c3c','#2ecc71'])
        st.pyplot(fig)

    with right_column:
        st.subheader("💬 Source Tweets Document Stream")

        if selected_sentiment != "ALL":
            filtered_df = df[df['sentiment'] == selected_sentiment]
        else:
            filtered_df = df

        for index, row in filtered_df.head(50).iterrows():
            current_sentiment = str(row['sentiment']).upper()
            color = "#2ecc71" if "POS" in current_sentiment else "#e74c3c" if "NEG" in current_sentiment else "#95a5a6"

            st.markdown(f'''
            <div style="border-left: 5px solid {color}; padding: 12px; margin-bottom: 10px; background-color: #f8f9fa; border-radius: 4px;">
                <p style="margin: 0; font-size: 14px; color: #2c3e50;">{row['clean_text']}</p>
                <span style="font-size: 11px; font-weight: bold; color: {color};">Classification: {row['sentiment']}</span>
            </div>
            ''', unsafe_allow_html=True)

except Exception as e:
    st.error(f"Execution Error: {e}")
""")

print("\n4/4: Opening tunnel...")
tunnel_password = urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip()

print("="*50)
print(f"👉 YOUR SITE PASSWORD (Endpoint IP): {tunnel_password}")
print("👉 PLEASE CLICK THE BLUE LINK BELOW AND ENTER THE PASSWORD")
print("(If you see a 'Failed to fetch' error when the site opens, refresh the page with CTRL + F5)")
print("="*50)

!streamlit run app.py --server.port 8505 & lt --port 8505